web:
    image: nginx:latest
    ports:
        - "8989:80"
    volumes:
        - ./src:/var/www/public
        - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./src:/var/www/public