web:
    image: nginx:latest
    ports:
        - "8989:80"
    volumes:
        - ./src:/var/www/
        - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: ./dockerfiles/php
    volumes:
        - ./src:/var/www/