version: '3'

services:
  webserver:
    build: ./dockerfiles/nginx
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpapp
  phpapp:
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/
  mysqldb:
    image: mysql:5.6
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./configs/mysql.conf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
  redis:
    image: redis:alpine3.12
    restart: always
    ports:
      - "16379:6379"

