version: '3'

services:
  webserver:
    build: ./dockerfiles/nginx
    ports:
      - "8989:80"
    volumes:
      - ./src:/var/www/
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpapp
  phpapp:
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/